# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/SW/Vivado_Projetcs/AES_Core/AES_Core.srcs/sources_1/bd/aes128_zynq_interface/ip/aes128_zynq_interface_xbar_0/aes128_zynq_interface_xbar_0.xci
# IP: The module: 'aes128_zynq_interface_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/SW/Vivado_Projetcs/AES_Core/AES_Core.gen/sources_1/bd/aes128_zynq_interface/ip/aes128_zynq_interface_xbar_0/aes128_zynq_interface_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'aes128_zynq_interface_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/SW/Vivado_Projetcs/AES_Core/AES_Core.srcs/sources_1/bd/aes128_zynq_interface/ip/aes128_zynq_interface_xbar_0/aes128_zynq_interface_xbar_0.xci
# IP: The module: 'aes128_zynq_interface_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/SW/Vivado_Projetcs/AES_Core/AES_Core.gen/sources_1/bd/aes128_zynq_interface/ip/aes128_zynq_interface_xbar_0/aes128_zynq_interface_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'aes128_zynq_interface_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
