
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_AXI_GPIO_CTRL_STAT_DEVICE_ID,
		XPAR_AXI_GPIO_CTRL_STAT_BASEADDR,
		XPAR_AXI_GPIO_CTRL_STAT_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_CTRL_STAT_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_QWORD1_I_DEVICE_ID,
		XPAR_AXI_GPIO_QWORD1_I_BASEADDR,
		XPAR_AXI_GPIO_QWORD1_I_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_QWORD1_I_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_QWORD1_O_DEVICE_ID,
		XPAR_AXI_GPIO_QWORD1_O_BASEADDR,
		XPAR_AXI_GPIO_QWORD1_O_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_QWORD1_O_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_QWORD2_I_DEVICE_ID,
		XPAR_AXI_GPIO_QWORD2_I_BASEADDR,
		XPAR_AXI_GPIO_QWORD2_I_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_QWORD2_I_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_QWORD2_O_DEVICE_ID,
		XPAR_AXI_GPIO_QWORD2_O_BASEADDR,
		XPAR_AXI_GPIO_QWORD2_O_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_QWORD2_O_IS_DUAL
	}
};


