# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/aes128_zynq_interface/aes128_zynq_interface.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes128_zynq_interface || ORIG_REF_NAME==aes128_zynq_interface} -quiet] -quiet

# IP: bd/aes128_zynq_interface/ip/aes128_zynq_interface_zynq_ultra_ps_e_0_0/aes128_zynq_interface_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes128_zynq_interface_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==aes128_zynq_interface_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/aes128_zynq_interface/ip/aes128_zynq_interface_axi_gpio_0_0/aes128_zynq_interface_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes128_zynq_interface_axi_gpio_0_0 || ORIG_REF_NAME==aes128_zynq_interface_axi_gpio_0_0} -quiet] -quiet

# IP: bd/aes128_zynq_interface/ip/aes128_zynq_interface_axi_gpio_1_0/aes128_zynq_interface_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes128_zynq_interface_axi_gpio_1_0 || ORIG_REF_NAME==aes128_zynq_interface_axi_gpio_1_0} -quiet] -quiet

# IP: bd/aes128_zynq_interface/ip/aes128_zynq_interface_axi_gpio_2_0/aes128_zynq_interface_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes128_zynq_interface_axi_gpio_2_0 || ORIG_REF_NAME==aes128_zynq_interface_axi_gpio_2_0} -quiet] -quiet

# IP: bd/aes128_zynq_interface/ip/aes128_zynq_interface_axi_gpio_3_0/aes128_zynq_interface_axi_gpio_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes128_zynq_interface_axi_gpio_3_0 || ORIG_REF_NAME==aes128_zynq_interface_axi_gpio_3_0} -quiet] -quiet

# IP: bd/aes128_zynq_interface/ip/aes128_zynq_interface_axi_gpio_4_0/aes128_zynq_interface_axi_gpio_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes128_zynq_interface_axi_gpio_4_0 || ORIG_REF_NAME==aes128_zynq_interface_axi_gpio_4_0} -quiet] -quiet

# IP: bd/aes128_zynq_interface/ip/aes128_zynq_interface_xbar_0/aes128_zynq_interface_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes128_zynq_interface_xbar_0 || ORIG_REF_NAME==aes128_zynq_interface_xbar_0} -quiet] -quiet

# IP: bd/aes128_zynq_interface/ip/aes128_zynq_interface_ps8_0_axi_periph_0/aes128_zynq_interface_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes128_zynq_interface_ps8_0_axi_periph_0 || ORIG_REF_NAME==aes128_zynq_interface_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/aes128_zynq_interface/ip/aes128_zynq_interface_rst_ps8_0_100M_0/aes128_zynq_interface_rst_ps8_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes128_zynq_interface_rst_ps8_0_100M_0 || ORIG_REF_NAME==aes128_zynq_interface_rst_ps8_0_100M_0} -quiet] -quiet

# IP: bd/aes128_zynq_interface/ip/aes128_zynq_interface_aes128_wrapper_0_0/aes128_zynq_interface_aes128_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes128_zynq_interface_aes128_wrapper_0_0 || ORIG_REF_NAME==aes128_zynq_interface_aes128_wrapper_0_0} -quiet] -quiet

# IP: bd/aes128_zynq_interface/ip/aes128_zynq_interface_auto_ds_0/aes128_zynq_interface_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes128_zynq_interface_auto_ds_0 || ORIG_REF_NAME==aes128_zynq_interface_auto_ds_0} -quiet] -quiet

# IP: bd/aes128_zynq_interface/ip/aes128_zynq_interface_auto_pc_0/aes128_zynq_interface_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes128_zynq_interface_auto_pc_0 || ORIG_REF_NAME==aes128_zynq_interface_auto_pc_0} -quiet] -quiet

# IP: bd/aes128_zynq_interface/ip/aes128_zynq_interface_auto_ds_1/aes128_zynq_interface_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes128_zynq_interface_auto_ds_1 || ORIG_REF_NAME==aes128_zynq_interface_auto_ds_1} -quiet] -quiet

# IP: bd/aes128_zynq_interface/ip/aes128_zynq_interface_auto_pc_1/aes128_zynq_interface_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes128_zynq_interface_auto_pc_1 || ORIG_REF_NAME==aes128_zynq_interface_auto_pc_1} -quiet] -quiet

# XDC: e:/SW/Vivado_Projetcs/AES_Core/AES_Core.gen/sources_1/bd/aes128_zynq_interface/aes128_zynq_interface_ooc.xdc
